name: SonarQube-analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: sonarsource/sonar-scanner-cli:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Analysis
        run: sonar-scanner -Dsonar.projectKey="Keploy Java SDK" -Dsonar.sources=. -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_TOKEN} || true
